apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: joshgree/app-flux:dev-379a5933dd0e3587d5bd7e15726c157d9e40fcea-1676215686 # {"$imagepolicy": "flux-system:app-flux-dev"}
