apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: joshgree/app-flux:1.0.4-rc2 # {"$imagepolicy": "flux-system:app-flux-dev"}
