name: Build and Push prod
on:
  push:
    tags: [prod]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
         DOCKER_TAG=$(git describe --tags)-$(git rev-parse HEAD)-$(date +%s)
         echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
      - name: check its set
        run: |
          echo ${{ env.DOCKER_TAG }}