apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: joshgree/app-flux:main-fcd9576062e9a33f31ad40be09ead1e59dece25f-1676160799 # {"$imagepolicy": "flux-system:app-flux-prod"}
