apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: joshgree/app-flux:prod-1ce846cd5fd4f9fc4871263e5dcf091d919e7122-1676216423 # {"$imagepolicy": "flux-system:app-flux-prod"}
